name: E2E for cypress

on:
  push:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Clear cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        run: npm run testdemo:headless

      - name: Generate Mochawesome report
        run: npm run mochawesome-merge

      - name: Archive Mochawesome report
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-report
          path: /home/runner/work/SpreadTest/SpreadTest/mochawesome-report
