name: E2E for cypress

on:
  push:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          build: npm install
          start: npm run testdemo:headless

      - name: Generate Mochawesome report
        run: npm run mochawesome-merge

      - name: Archive Mochawesome report
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-report
          path: SpreadTest/mochawesome-report
