name: E2E for cypress on Chrome

on:
  push:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
          build: npm install
          start: npm run testdemo:headless

      - name: Generate test reports
        run: |
          npm run junit-merge
          npm run mochawesome-merge
